site_name: Bioinformatics course

theme:
    name: material
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    feature:
        tabs: false

pages:
    - Home: index.md
    - Proteins: proteins.md
    - Unix: unix.md
    - Project Organisation: project_organisation.md
    - Cloud Computing: cloud.md
    - Installing Software: software.md
    - Git: git.md
    - Command-line Blast: blast.md

markdown_extensions:
  - admonition

extra_css:
    - css/admonition.css
