site_name: Bioinformatics course
theme: cinder
pages:
    - Home: index.md
    - Unix: unix.md
    - Installing Software: software.md

markdown_extensions:
  - admonition

extra_css:
    - css/admonition.css
